### ISSUE TITLE
IPFS Meetup in NYC (March 30)

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#102]
#### IPFS Meetup

**What**: General hackathon, maybe some lightning talks, maybe some IPFS.bar or IPFS.coffee
**Where**: New York City
**When**: February 25th-28th (choose?)
**Who**:
 - @RichardLitt
 - @jbenet 

Anyone else interested?

---

Update: Tentative copy:

# First ever NYC IPFS Meetup!

IPFS -- the InterPlanetary File System -- is making the web faster, safer, decentralized, and more open. It is a new hypermedia distribution protocol, addressed by content and identities. Think Git + BitTorrent + The Web. IPFS is in use by thousands of developers, for all kinds of things from distributing files more efficiently, to making decentralized chat applications, to giving permanent addresses to content, to hosting content for Blockchains. IPFS is one of the hottest and fastest growing Open Source projects! You can learn more about IPFS at https://ipfs.io and https://github.com/ipfs/ipfs

This is the first IPFS NYC Meetup! And most of the core developers are here! Don't miss this opportunity to hang out with us! Join us for an exciting evening of p2p, filesystems, blockchains (bitcoin / ethereum), and apps. Lots of Go and Javascript!

- **Place: AWS Loft, 350 W Broadway, New York, NY 10013**
- **Time: 6pm to 8:30pm**
- **Format:** mingling, 5 short talks, more mingling and maybe hacking.
- **Drinks:** we will serve non-alcoholic drinks (too soon to get caterers or license)
- **Food:** we will have some snacks.

### IPFS and COOL DATA STRUCTURES - 5 short talks

**0. Quick Introduction to IPFS (5min).**

Juan Benet -- IPFS core developer and Protocol Labs -- will attempt a short but deep introduction to The IPFS Project. This should give enough context for newcommers to follow the rest of the talks.

**1. IPLD -- Merkle-linked JSON. (15min)**

Juan Benet will give an introduction to IPLD, a new standard for secure, serialized data on the web. IPLD is just JSON (or YAML, or CBOR) that has merkle-links -- meaning that links between objects link using a cryptographic hash. This gives the distributed security properties of Git and Blockchains to any data. This standard is one of the most powerful parts of IPFS, and will enable a wealth of new applications to emerge.

**2. uPort -- Identity Management with Ethereum and IPFS. (15min)**

Christian Lundkvist -- CTO of Consensys and author of many Ethereum applications -- will give an introduction to uPort, an exciting new decentralized Identity system. uPort uses programs on the Ethereum Blockchain and content on IPFS to maintain identity records that are permanent, uncensorable, and controlled only by you! The uPort attestation system allows third party authorities as well as peers to validate the user's information creating both a rich social fabric as well as powering solid KYC/AML systems in the financial sector.

**3. Mediachain -- distributed media metadata protocol. (15min)**

(TENTATIVE / UNCONFIRMED) Denis or Arkadiy? will give an introduction to Mediachain, a collaborative federated media metadata protocol that allows parties to make statements about creative works. The metadata statements are cryptographically signed by the contributor, timestamped in the Bitcoin blockchain, and stored in IPFS. The statements can then be looked up via perceptual search using an instance of the media itself. 

**4. Gx and Registry Mirror -- Package Management on IPFS. (20min)**

Jeromy Johnson and David Dias -- IPFS core developers and Protocol Labs -- will speak about Gx and reegistry-mirror, two exciting package management projects on top of IPFS. IPFS is fantastic for package managers, because of its decentralized, secure, and permanent linking. registry-mirror is a node.js module that makes it so you can install npm packages directly from IPFS, peer-to-peer! Gx is a new package manager on top of IPFS. It aims to be flexible, powerful, and simple. You can use it today to secure your Go dependencies!

**5. Orbit -- distributed p2p chat on IPFS. (15min)**

Samuli Poyhtari -- IPFS core developer and Protocol Labs -- will speak about Orbit, a distributed p2p chat on IPFS. Think decentralized Slack or IRC! This talk will demo it, discuss how it works, and its components. And we will discuss how we can build realtime apps on IPFS.

**Comment by mindhog** [comment]
Count me in!

**Comment by dysbulic** [comment]
I'm interested.

I'd still like to do something in DC, but have been dealing w/ life.

Perhaps something in conjunction w/ http://dc.opendataday.org March 4–5…

**Comment by chriscool** [comment]
I will probably be in NYC around April 4-5 for the Git Merge 2016 (http://git-merge.com/).
By the way GitHub announced a bunch of conferences for 2016: https://github.com/blog/2102-save-the-dates-github-events-in-2016

**Comment by jbenet** [comment]
I'm in

**Comment by RichardLitt** [comment]
@jbenet Know of any places we could host a meeting? If not, I'll scout around.

**Comment by mindhog** [comment]
I might be able to get a space in Google's NYC office if you guys are interested.  Any guesses as to how many people to expect?

**Comment by RichardLitt** [comment]
We can cap it at whatever: I expect less than 10, more than 5.

**Comment by denisnazarov** [comment]
:+1: @parkan

**Comment by jbenet** [comment]
- @RichardLitt not sure these dates work for me yet, as I may be in DC.
- @RichardLitt let's aim for 30-100 people. 
- We'll record some interesting talks.
- @mindhog Google would be great! But maybe too big for you. if not, email me at juan@ipfs.io for details
- Our friends at ConsenSys have also offered to host it at their office.
- I'll figure out dates that wfm this weekend + reach out to people about spaces.

---

- @chrislundkvist may be good to record a talk about uPort and the ID work you're doing? (or whatever else)
- @parkan may be good to record a talk about Mediachain -- either this one or next?

**Comment by jbenet** [comment]
- @RichardLitt not sure these dates work for me yet, as I may be in DC.
- @RichardLitt let's aim for 30-100 people. 
- We'll record some interesting talks.
- @mindhog Google would be great! But maybe too big for you. if not, email me at juan@ipfs.io for details
- Our friends at ConsenSys have also offered to host it at their office.
- I'll figure out dates that wfm this weekend + reach out to people about spaces.

---

- @christianlundkvist may be good to record a talk about uPort and the ID work you're doing? (or whatever else)
- @parkan may be good to record a talk about Mediachain -- either this one or next?

**Comment by parkan** [comment]
@jbenet I'll be out of town this day but totally down to speak at the next event -- I think we'll have more to show then, too. Any estimate for when that might be?

**Comment by RichardLitt** [comment]
Whoa, ok, that's a lot. Awesome! 

@jbenet Let us know ASAP when your dates are. You should be there! I also need to figure out when, as I have things on either side. 

Who can we get to record? And let me know if there's anything I can do, as soon as an obstacle arises.

**Comment by christianlundkvist** [comment]
@jbenet I'll be happy to give a talk on uPort/Identity and how IPFS plays into it. And ConsenSys would be very happy to host the meetup! We might be able to record, but not clear on that.

**Comment by boxxa** [comment]
Let me know as soon as you set a venue and date. Could possibly book a trip for the Friday 26 if it's just one day.

**Comment by mindhog** [comment]
I've been casually trying to locate the right people to contact to host this at Google, but  @christianlundkvist if you guys are good to do this at ConsenSys I'll happily relinquish it.

If there ends up being a problem with the ConsenSys plan let me know and I'll resume efforts :-)

**Comment by jamescarlyle** [comment]
I'm in NYC that week, and keen to come along.

**Comment by christianlundkvist** [comment]
I'll put the word out and see what they say. We are happy to do it here, should I try something the week Feb 22nd to 26th?

**Comment by jeffscottward** [comment]
The technical heads of UPort, IPFS, and R3 in the same room, oh my :)

**Comment by boxxa** [comment]
We should stream this over IPFS. Doesn't someone have a prototype of streaming video working?

**Comment by christianlundkvist** [comment]
We can do Feb 25th but we have a limit of max 50-60 ppl in the ConsenSys office. Would that work @jbenet @RichardLitt?

**Comment by christianlundkvist** [comment]
@jbenet @RichardLitt: Bump.

Does the above sound OK? IPFS meetup Feb 25th in the ConsenSys office, max 50 ppl?

**Comment by NodeGuy** [comment]
I'd like to join.

**Comment by j-h-scheufen** [comment]
Would love to come as well.

**Comment by christianlundkvist** [comment]
@jbenet @richardlitt I kind of have to know if you guys are ok with the date & limits otherwise I won't be able to book it. Might be too late already for the 25th... :(

**Comment by jbenet** [comment]
Hey everyone, sorry about my silence! -- im drowning in github notifs.

@christianlundkvist that's awesome, thank you for offering a place! Do you think it makes sense, given our failure to push on this so far, to invite people for so soon? The 25th is 2 days from now; maybe we should push off to some time in march? What do you think? (Hate to cause "on and off and on" trouble, after you getting the space for us).

What may work, since @jamescarlyle is in NYC that week, is for us to have a small meetup anyway, and talk about things? But not sure that having recorded talks this soon makes sense? Getting ~50 people to show up in 2 days notice is non trivial.

@christianlundkvist i'll email you to have this discussion in faster throughput.

Sorry again for silence!

**Comment by lgierth** [comment]
I'll be there in the second half of March too :)

**Comment by jbenet** [comment]
Maybe what we should do is this: if 15+ people want to come on the 25th (this thursday!), we should have it, else let's just postpone till 2nd or 3rd week of march?

**Comment by RichardLitt** [comment]
Going to be hard to get that amount of people in NY on such a short notice, and also hard to decide when to cut off about how to book it. I can't make it, either. I think postponing might work best, at this point. 

March 18th?

**Comment by chriscool** [comment]
I will be in NYC from March 30 to April 8. I will attend the Git Developer Summit on April 4 and the Git Merge on April 5 (in NYC).

**Comment by NodeGuy** [comment]
I vote for postponing.

**Comment by christianlundkvist** [comment]
Postponing sounds good to me too. We should be able to arrange something then.

**Comment by jbenet** [comment]
Ok let's postpone. Let's pick a date. Whether or not we do one early march, It may make sense to do one in April, close to both Git Merge and the NYC Blockchain Workshop (first week of april too i think). Maybe we could do both.

**Comment by christianlundkvist** [comment]
Other dates could be March 23rd

**Comment by RichardLitt** [comment]
March 16th works better for me, giving a Papers We Love talk in Boston on the 23rd. :)

**Comment by christianlundkvist** [comment]
So after (F2F!) discussions with @richardlitt and @jbenet it looks like it may be the 23rd after all. More to come...

**Comment by se3000** [comment]
@christianlundkvist any update on this?

**Comment by christianlundkvist** [comment]
@se3000 - 23rd is out, it might be the week of the 28th or after.

**Comment by christianlundkvist** [comment]
@jbenet @RichardLitt Can you guys do Wed March 30th?

**Comment by lgierth** [comment]
@christianlundkvist March 30th would be great -- we've booked a location for 29th or 30th. I'm writing stuff up for them right now.

**Comment by christianlundkvist** [comment]
@lgierth If you are organizing it you can also use ConsenSys space - 50 ppl max

**Comment by jmsmcfrlnd** [comment]
I am interested in 3/29 or 3/30 in NYC.

**Comment by jbenet** [comment]
@christianlundkvist ah thanks very much! (thought couldn't this week)

Well, we can use either the ConsenSys office (Brooklyn, ~Morgan) or the AWS Loft (~100 people, in Manhattan, SOHO). I like the ConsenSys office. the AWS Loft may be easier (dedicated space, we dont bother). Loft space is more event-y, has presentation room with projector, and then an area with many couches. ConsenSys space is guaranteed to have many awesome people around.

How much work is this on you guys Christian? We can take care of all org, but i mean telling people, not being able to use the space, etc? 

Maybe we can say Loft for now, and if <50 ppl RSVP by Tue we can move it to ConsenSys?

**Comment by jbenet** [comment]
Tentative copy:

# First ever NYC IPFS Meetup!

IPFS -- the InterPlanetary File System -- is making the web faster, safer, decentralized, and more open. It is a new hypermedia distribution protocol, addressed by content and identities. Think Git + BitTorrent + The Web. IPFS is in use by thousands of developers, for all kinds of things from distributing files more efficiently, to making decentralized chat applications, to giving permanent addresses to content, to hosting content for Blockchains. IPFS is one of the hottest and fastest growing Open Source projects! You can learn more about IPFS at https://ipfs.io and https://github.com/ipfs/ipfs

This is the first IPFS NYC Meetup! And most of the core developers are here! Don't miss this opportunity to hang out with us! Join us for an exciting evening of p2p, filesystems, blockchains (bitcoin / ethereum), and apps. Lots of Go and Javascript!

- **Place: AWS Loft, 350 W Broadway, New York, NY 10013**
- **Time: 6pm to 8:30pm**
- **Format:** mingling, 5 short talks, more mingling and maybe hacking.
- **Drinks:** we will serve non-alcoholic drinks (too soon to get caterers or license)
- **Food:** we will have some snacks.

### IPFS and COOL DATA STRUCTURES - 5 short talks

**0. Quick Introduction to IPFS (5min).**

Juan Benet -- IPFS core developer and Protocol Labs -- will attempt a short but deep introduction to The IPFS Project. This should give enough context for newcommers to follow the rest of the talks.

**1. IPLD -- Merkle-linked JSON. (15min)**

Juan Benet will give an introduction to IPLD, a new standard for secure, serialized data on the web. IPLD is just JSON (or YAML, or CBOR) that has merkle-links -- meaning that links between objects link using a cryptographic hash. This gives the distributed security properties of Git and Blockchains to any data. This standard is one of the most powerful parts of IPFS, and will enable a wealth of new applications to emerge.

**2. uPort -- Identity Management with Ethereum and IPFS. (15min)**

Christian Lundkvist -- CTO of Consensys and author of many Ethereum applications -- will give an introduction to uPort, an exciting new decentralized Identity system. uPort uses programs on the Ethereum Blockchain and content on IPFS to maintain identity records that are permanent, uncensorable, and controlled only by you! The uPort attestation system allows third party authorities as well as peers to validate the user's information creating both a rich social fabric as well as powering solid KYC/AML systems in the financial sector.

**3. Mediachain -- distributed media metadata protocol. (15min)**

(TENTATIVE / UNCONFIRMED) Denis Nazarov (or someone else) -- Founder of Mine -- will give an introduction to Mediachain, a collaborative federated media metadata protocol that allows parties to make statements about creative works. The metadata statements are cryptographically signed by the contributor, timestamped in the Bitcoin blockchain, and stored in IPFS. The statements can then be looked up via perceptual search using an instance of the media itself. 

**4. Gx and Registry Mirror -- Package Management on IPFS. (20min)**

Jeromy Johnson and David Dias -- IPFS core developers and Protocol Labs -- will speak about Gx and reegistry-mirror, two exciting package management projects on top of IPFS. IPFS is fantastic for package managers, because of its decentralized, secure, and permanent linking. registry-mirror is a node.js module that makes it so you can install npm packages directly from IPFS, peer-to-peer! Gx is a new package manager on top of IPFS. It aims to be flexible, powerful, and simple. You can use it today to secure your Go dependencies!

**5. Orbit -- distributed p2p chat on IPFS. (15min)**

Samuli Poyhtari -- IPFS developer and Protocol Labs -- will speak about Orbit, a distributed p2p chat on IPFS. Think decentralized Slack or IRC! This talk will demo it, discuss how it works, and its components. And we will discuss how we can build realtime apps on IPFS.

**Comment by jbenet** [comment]
We should make either an Eventbrite or an Attending.io or a Meetup.com page. Meetup.com is painful and sucks, but is nice and regular. Eventbrite is simple and good. Attending.io is beautiful but we had glitches a year ago. we could give it another try!

**Comment by jbenet** [comment]
I vote we use either this image, or a similar one on a NYC background

![](https://cdn-images-1.medium.com/max/2000/1*czZJ7mvEAqL4wNAg-jt9Ow.jpeg)

![](https://static.pexels.com/photos/2324/skyline-buildings-new-york-skyscrapers.jpg)
![](https://upload.wikimedia.org/wikipedia/commons/3/31/Vista_a%C3%A9rea_de_Times_Square_desde_el_Empire_State_Building.jpg)
![](https://static.pexels.com/photos/291/black-and-white-city-landmark-lights.jpg)

**Comment by jbenet** [comment]
Also @christianlundkvist and everyone im so sorry for being so horribly late to organizing this meetup! It ended up being useful, as now a lot more ipfs devs will be around.

**Comment by jbenet** [comment]
cc @diasdavid @whyrusleeping @haadcode @dignifiedquire @noffle @RichardLitt @chriscool @parkan @denisnazarov @yusefnapora @bigs @muneeb-ali @guylepage3 @shea256 @jcnelson @jeffscottward @simondlr @bhny @nitinics @rschulman and bring/tag any others.

**Comment by shea256** [comment]
Awesome, thanks @jbenet - would love to make it out!

The Onename team has an event on 3/30 but I can come any other day that week or the following week.

**Comment by lgierth** [comment]
cc @grobie @werecat @azlyth @ksnieck @lukevers

**Comment by christianlundkvist** [comment]
@jbenet 
> How much work is this on you guys Christian? We can take care of all org, but i mean telling people, not being able to use the space, etc?

Not much work at all! I just need to tell people in advance we're having a meetup.

> Maybe we can say Loft for now, and if <50 ppl RSVP by Tue we can move it to ConsenSys?

Yeah, sounds good!

**Comment by christianlundkvist** [comment]
> Also @christianlundkvist and everyone im so sorry for being so horribly late to organizing this meetup! It ended up being useful, as now a lot more ipfs devs will be around at this later date.

No worries! :smile: We're all super busy!

**Comment by creckhow** [comment]
This is looking great @jbenet let me know how I can help with marketing & set-up and which direction you go in for info dissemination (eventbrite or meetup, etc.). Thanks @christianlundkvist for pulling me in on this -- excited to host you all at ConsenSys HQ!

**Comment by creckhow** [comment]
[...and after you knock this one out of the park @jbenet let's do a repeat show in Boston? I've been chatting with @RichardLitt a bit about this -- and can likely get us a space a MIT. ]

But Brooklyn first! :smile:

**Comment by noffle** [comment]
![ipfs](http://www.stephenwhitmore.com/tmp/ipfs_aus.jpg)

**Comment by christianlundkvist** [comment]
@jbenet If you use the IPFS image from the Medium article make sure you have attribution to Bogdan Burcea.

**Comment by christianlundkvist** [comment]
@noffle Reminds me of Akira!

http://www.space538.org/sites/default/files/styles/thumb_700x400/public/photos/AKIRA1.jpg?itok=CCuic6Du

**Comment by noffle** [comment]
@christianlundkvist: If all goes well, I expect our meetup will end very similarly to Akira too!

**Comment by shea256** [comment]
Hey @jbenet we have another event at 6pm but we'd love to come by a bit after, around 7pm or 730pm. Can you please add us to the list of short talks near the end? What's the time frame for the talks?

**Comment by jbenet** [comment]
@shea256 

Good to see you today! yes can add as discussed, can you do it in 10-12min? we've to be out of AWS Loft by 8:30 and want to make sure to have some hangout time after talks (this may be a reason for doing it at ConsenSys instead? omg variables and constraints!). For now we'll stick with AWS Loft and we'll be strict on time. 

Also please note that all talks of the night have to do with IPFS and/or IPLD. (it's not a general distributed sys meetup -- we should run one of those, but that should be a sep event). There is good overlap on identity with the uPort talk from @christianlundkvist -- and I personally think there's heavy overlap worth exploring in:

- representing blockstack chain with IPLD
- replicating blockstack data with IPFS
- onename profile data addressed on IPFS
- blockstack name resolution for IPFS naming (`/ipns/<blockstack-name>.<blockstack-tld>/foo/bar/baz`)

**Comment by jbenet** [comment]
@christianlundkvist and if you want to discuss ujomusic too, or whatever, feel free. I'm personally interested in uPort but a lot of people will care about other things. whatever is most useful.

**Comment by jbenet** [comment]
Hey @creckhow! thanks!! i think right now we're booked to do AWS Loft (because we're not sure if we'll go over 50+ people, and we wanted to check out that space-- it's well setup for recording talks), but if we could stay at consensys office longer time (say 6-9:30/10), maybe we should reconsider? (we have not sent the invite/flyer yet, so we still can. we plan to do that later today).

**Comment by creckhow** [comment]
Ok. The ConsenSys office is still available and we're OK to keep IPFSing till 9:30 or 10. If that's appealing let me know @jbenet.

**Comment by shea256** [comment]
@jbenet I think talking about blockstack name resolution for IPFS naming would be awesome. Great fit and very relevant.

**Comment by jbenet** [comment]
Thanks very much @creckhow! @RichardLitt and i discussed and since we dont have a good estimate on RSVP numbers yet, we think it's safer to go with AWS Loft for now? (we can go up to 150ppl max there) but if monday rolls around and there's <50 RSVPs, and everyone prefers ConsenSys office (most speakers would i think), we should move it there? (sorry for deferring decisions to last possible moment so much, if you need to decide today, let's just roll with AWS Loft?)

**Comment by jbenet** [comment]
@shea256 SGTM, can you give me a description to fit these: https://github.com/ipfs/community/issues/102#issuecomment-200731738 ? (title, description with presenter name pls)

**Comment by RichardLitt** [comment]
# [Sign up on Eventbrite here!](https://www.eventbrite.com/e/ipfs-new-york-meetup-tickets-24194265700)

**Comment by creckhow** [comment]
@jbenet whatever works for you -- I've got the ConsenSys office blocked out for this event 6pm and on Wednesday so if you'd like to shift over if attendance is low, it'd be no big deal.

Also, let me know if you'd like me to blast this out over ConsenSys social media.

**Comment by christianlundkvist** [comment]
@jbenet - I'll talk about uPort and give a quick demo 😃

**Comment by cpacia** [comment]
@jbenet I'll be able to come if you want me to talk about OB.

**Comment by chriscool** [comment]
My plane arrives at 7:15pm on March 30 at the JFK airport. So if you guys go to the ConsenSys office or another place after 8:30, please tell me, I will try to make it.

**Comment by shea256** [comment]
@jbenet @RichardLitt should I send you a short writeup for the talk on Blockstack w/ IPNS so you can add it to the Eventbrite?

**Comment by chriscool** [comment]
PS: my plane was booked a long time ago for the Git Merge (April 4 and 5) and they did let me change it to take an earlier plane :-(

**Comment by RichardLitt** [comment]
They didn't? :(

**Comment by RichardLitt** [comment]
@shea256 Please do! richardlitt at ipfs, or my normal email. I'll add it asap.

**Comment by parkan** [comment]
Very excited for this! The header image is quite pretty but it does make me think of this

![ceqexe0w8aa0y1x](https://cloud.githubusercontent.com/assets/204986/14090640/87da170a-f509-11e5-8a32-9b8c637096fe.jpg)

and/or

![akiraexplosion_360](https://cloud.githubusercontent.com/assets/204986/14090675/af9a447c-f509-11e5-80e8-0f4f535251ef.jpg)

**Comment by muneeb-ali** [comment]
Planning to come and looking forward to it!

**Comment by jbenet** [comment]
@cpacia that would be excellent, please do! Packed schedule, but excellent one.

**Comment by cpacia** [comment]
@RichardLitt should I email you some slides as well?

**Comment by RichardLitt** [comment]
@cpacia Just an abstract is fine! Bring the slides tomorrow. :)

**Comment by jmsmcfrlnd** [comment]
Would the presenters be open to sharing their slide decks somewhere?

**Comment by parkan** [comment]
@jmsmcfrlnd shared mine here, though I'm working on a writeup + waiting for the video http://slides.com/arkadiykukarkin/mediachainheartsipfs

**Comment by jmsmcfrlnd** [comment]
Thank you @parkan! And I am happy to be patient and wait for the proper package you describe above.  And I just realized that all could be shared on @ipfs :-) somehow... So I best get my @ipfs skills sharpened up.

**Comment by haadcode** [comment]
My slides about [Orbit](https://github.com/haadcode/orbit) are here: https://ipfs.io/ipfs/QmWsmxViMkWeeUXCJdhDSnQwPVuvDoHGKKazUk3afLfi48

**Comment by RichardLitt** [comment]
Thanks everyone for coming!

**Comment by shea256** [comment]
Yes and thank you @RichardLitt @jbenet for having us! We're also hosting a Blockstack NYC Meetup on May 4th and would love to see you if you're around: http://www.meetup.com/Blockstack-NYC/events/230401990/
