### ISSUE TITLE
LGTM to RFM label github bot

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/community#138]
We have `Looks Good To Me` system in many repos, it would be great to have a bot that would remove `needs review` tag from the issues (possibly configurable) and adding `RFM` (also configurable). If someone from the team writes `LGTM` at the begging of comment (so comments like that "Apart from ... LGTM" don't have their labels changed).

@RichardLitt

**Comment by Kubuxu** [comment]
Also it would be nice if there was possibility of it waiting for two people to `SMGT` (Seems Good To Me)

**Comment by RichardLitt** [comment]
It would also be good to have a bot to automatically update links in READMEs. Discussed briefly here: https://github.com/dignifiedquire/aegir/pull/53#event-779298476.

**Comment by jbenet** [comment]
- Bot to remove the "needs review" tag is fine, though I think in general
it won't be always clear: some things need more than 1 "LGTM" because it's
a big important change or involves multiple people. Maybe it could parse
something like:

```
RFC @jbenet @whyrusleeping
```
Which would assign those two people, and then:
- unassign them when they have "LGTM"
- remove "Needs Review" when all have LGTMed
- re-assign the original author.


Also:

- Please no bots ever saying RFM. That is an explicit action that should
have responsibility of devs calling it. Critical to avoid problems.
