### ISSUE TITLE
NYC Study Group in October

### ISSUE THREAD

**Issue by chadoh** [ipfs/community#186]
I gave a talk two weeks ago at NYC React that spent a lot of time discussing IPFS: https://www.youtube.com/watch?v=wxDn1XMVwNE

One of the attendees of the talk (@bruno78) expressed interest in starting a study group to explore Distributed Web & related tech in more depth. I suspect there could be strong support for such a group in NYC! For the first meeting, I was thinking it would be awesome to do a workshop on Deploying Your First Front-End App To IPFS. 

Tentative date for meetup: **Thu, 27 Oct** as part of [the NYC React meetup](http://www.meetup.com/NYC-Javascript-React-Group/events/226336204/) or **Wed, 26 Oct** as the start of something new.

**Comment by chadoh** [comment]
btw: I'd love feedback on ways I can improve my talk! I'm sure there are things I missed.

**Comment by flyingzumwalt** [comment]
FYI @jadrian and I are currently running a 10-week distributed web study
group through Code for Philly. It started last week.

About the project: https://codeforphilly.org/projects/dat_tables

Where we're putting all of the study/workshop materials:
https://codeforphilly.github.io/decentralized-data/

After the series, I plan to pull that info together in a Distributed Web
Primer. I sketched an outline for the primer as a git book here:
https://www.gitbook.com/book/flyingzumwalt/decentralized-web-primer
(Open the book & look at the table of contents. It's just an outline right
now).

Could your study group help us refine the primer and/or workshop materials?

I think I could come up to NYC on the 27th.

**Comment by chadoh** [comment]
@flyingzumwalt your course looks awesome! Who do you see as the target audience for it? (Also, I did not know about Noms and I'm intrigued!)

The target audience for the workshop I'm attempting to organize are people who already have experience building front-end apps on the current web. Which is where I'm at. And I'd like to learn how to deploy a front-end app to IPFS, so a workshop on it seems very helpful 😝  If there's enough interest in this to turn it into a whole workshop series, I was thinking it would go sort of like this:

1. Deploy your favorite version of TodoMVC to IPFS (simple front-end-only app with no backing data store or server-side logic)
2. Add a data store like Noms or BigchainDB, so that data in my IPFS-hosted Todo app can sync between my computer and my phone (or my phone & your phone)
3. Add "server-side" (aka incorruptible) logic to the app with Ethereum. Maybe users can pay each other to take care of todos, idk.

It seems like _maybe_ your Class#8 on 2016-11-29, "IPFS: hands-on & theory", might be close to what I was envisioning for my DApp Workshop 1. And _maybe_ your Class#5 on 2016-11-01, "Version Control Week III: Noms hands-on", might be close to my DApp Workshop 2. I definitely think we could help refine your primer & some workshop materials. What do you think?

Also, I'm actually not in NYC. I'm in the city of Lancaster and work for a company with an office in NYC. I lived in Philly until this past April. I'm definitely interested in coming in for some of your classes. The Noms hands-on seems like the first thing that might be applicable to where I'm at, since the other stuff seems more introductory. Do you think that would make sense for me?

**Comment by RichardLitt** [comment]
I am also planning on coming up to NYC for this. :) I think October 26th makes more sense; I'm not sure this will fit easily into the React workshop.

**Comment by bruno78** [comment]
Your course does look great,  @flyingzumwalt
<https://github.com/flyingzumwalt>! If I were in Philly I'd definitely
would want to join you guys for that! Perhaps we could follow the
guidelines of @flyingzumwalt <https://github.com/flyingzumwalt>'s course
and include the how to upload a front-end app to IPFS. Perhaps once we have
the uploaded app we learn how use noms with it.... :-D

On Thu, Oct 13, 2016 at 10:40 AM, Richard Littauer <notifications@github.com

**Comment by flyingzumwalt** [comment]
Hey @chadoh and @bruno78. Sorry for the delay. We were in Quarterly Meetings all of last week.

I like the structure that @chadoh proposes and I definitely want to help you create learning materials for people to use in a workshop like that. The Code for Philly program won't be focusing on distributed apps, so it will only be covering fundamentals. It's just focusing on allowing you to write an IPFS adapter for NOMS. That means we will cover 

* The IPFS model
* Merkle DAGs and Content-addressable storage
* Running IPFS nodes 
* Manually creating blocks on IPFS

We will also cover adding files to IPFS, reading files from IPFS, and pinning files on your IPFS node. We might also cover IPFS gateways.  

In order to deal with distributed apps we will have to also cover concepts like [consistency in distributed systems](http://book.mixu.net/distsys/), [CRDTs](http://christophermeiklejohn.com/crdt/2014/07/22/readings-in-crdts.html) [https://github.com/ipfs/notes/issues/40][https://github.com/ipfs/notes/issues/108][https://github.com/ipfs/notes/issues/161], and [pubsub](https://github.com/ipfs/notes/issues/154).  That was too much for us to bite off with the Code for Philly group but I am eager to work on producing docs that cover that subject matter so it will be wonderful to help you tackle it with the NYC group.

@chadoh as far as attending the Philly group, we have structured it as a stable cohort of people who all started together a few weeks ago and will be learning together for the next few months.  If you want to come to _all_ of the remaining sessions then we'll let you join late. Otherwise, it will probably be too disruptive to have new people appearing and disappearing on some weeks.  The target audience for that program is developers who want to "level up", getting experience working on teams and tackling hard topics together, so it's a lower experience level than you're aiming for in NYC. The IPFS focus is secondary - we could have worked on anything but I want to test out ways to teach people about things like Merkle DAGs and the decentralized web. I thought this was a good opportunity to put the workshop materials in front of real people to see what works or doesn't work for them.

**Comment by RichardLitt** [comment]
@chadoh Listened to your talk today; love it. Great job. 

When would be best for this? I can't come up on the 26th - I'm giving a talk in DC that day. The 27th would work with NYC React, you say, but would we be able to have a hackathon around that? Are you still interested in having something happen in NYC?

**Comment by flyingzumwalt** [comment]
@chadoh are you planning to do this in NYC on the 27th? If so, @RichardLitt and I will put it on our calendars.

**Comment by flyingzumwalt** [comment]
If the training for "Burning Man staff and colleagues" on November 16-18 is compelling, I could probably get us invited. Might be cool, but they will probably dive deep into subject matter that's not relevant for us.

**Comment by chadoh** [comment]
@flyingzumwalt @RichardLitt Sorry for the delay in response! Unfortunately, this coming week is already the 26th & 27th, and it turns out for personal reasons for be a bad time to come up to NYC overnight. It will continue to be a bad time for me for the entire over-booked month of November. If we stick with trying to meet at the end of a month, that pushes us back to January, which I don't like at all. How's early December for y'all? Maybe December 1 or 8?

**Comment by RichardLitt** [comment]
Ah, OK. December 1st or 8th might work; I won't be in the area, however. @flyingzumwalt may be able to come up for that?

**Comment by em-ly** [comment]
Just want to know that there is currently a soft conflict for both @RichardLitt and @flyingzumwalt for the Dec 8th date - nothing's confirmed yet but want to make sure that's factored into scheduling before things become concrete.

**Comment by bruno78** [comment]
Hey guys,

What happened yesterday was one more reason to learn the depths
of decentralized Internet. I wish we could have an entire course like
Matt's.

**Comment by flyingzumwalt** [comment]
@bruno78 I'm working on it!

**Comment by meyerscr** [comment]
Is there a mailing list or is this the extend of the organizing? I worked with nycmesh.net, and we're very interested in ipfs.

**Comment by RichardLitt** [comment]
@meyerscr This is it; no mailing list at the moment. You can always catch us on IRC, too, for live conversations.

**Comment by meyerscr** [comment]
Cool. Thanks. I'll try to be at the next one. What's the IRC?

**Comment by RichardLitt** [comment]
#ipfs on Freenode. :)

**Comment by diasdavid** [comment]
Did this happened? Can someone do a writeup? :)

**Comment by flyingzumwalt** [comment]
@diasdavid it didn't happen. We also figured out that a lot of the people who were interested actually live closer to Philadelphia than NYC. I plan to form a Philadelphia meetup group in Q1 (currently too busy running [dat-jawn](http://datjawn.com)

**Comment by RichardLitt** [comment]
It would be great to see it happen, though! I am going to close this as a New York meet up in October is no longer possible; open up another thread for New York if anyone wants to have a meetup there.
