### ISSUE TITLE
Discourse thinks urls to Github are spam

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#252]
![image](https://cloud.githubusercontent.com/assets/1211152/24896324/ab5dd8f0-1e94-11e7-9962-56367fa36bd2.png)

**Comment by lidel** [comment]
@flyingzumwalt I feel default anti-spam protections provided by Discourse should be eased up a little bit. 
It is quite discouraging when someone refers to something at github, and gets flagged as spam 😕 
Github resources are nearly always a valuable input.

**Comment by VictorBjelkholm** [comment]
Yeah, it wasn't because it was specifically referring to Github but rather that @diasdavid made two posts with three links to the same site, which triggered the spam filter. The limit has already been raised and shouldn't be triggered anymore. Also, the posts were flagged but not hidden/removed, so no action required there.

We should figure out other anti-spam values as a part of https://github.com/ipfs/community/issues/250, which we use as the issue for the progress of the forum.
