### ISSUE TITLE
Measuring Community Growth (npm)

### ISSUE THREAD

**Issue by mikeal** [ipfs/community#345]
I put together a little code (below) to try and estimate activity in the npm ecosystem.

The code does an npm search for `"ipfs"` and then pulls in the download metrics for all of those modules.

There's a few problems with this method. 

* Relying on search for `"ipfs"` isn't a complete list of packages. We'd want some more sophisticated code here that pulled in any modules depending on ipfs and ipfs related modules to get a complete list.
* Using download metrics is likely to double-count a lot of modules and dependencies. Local caching helps iron some of this out but spikes we see around releases show up as exponential increases when they are more likely to really be gradual increases.

<img width="808" alt="screen shot 2018-10-13 at 11 12 36 am" src="https://user-images.githubusercontent.com/579/46904289-e7623c00-ced9-11e8-879e-b7f9a22c1ced.png">

Logorithmic scale (Base 10) irons out some of the noise.

<img width="801" alt="screen shot 2018-10-13 at 11 11 50 am" src="https://user-images.githubusercontent.com/579/46904286-d5809900-ced9-11e8-8678-ba07d3d14441.png">

Whatever we started doing in June (releasing more) is clearly having an effect. This effect appears to be larger than *just* the downloads of ipfs itself, it's causing more overall activity across npm in ipfs related modules.

Here's the code.

```javascript
const bent = require('bent')
const registry = require('npm-stats')()

const npmsearch = bent('http://npmsearch.com', 'json')

const createCsvStringifier = require('csv-writer').createObjectCsvStringifier

const search = async term => {
  let allresults = []
  let result = {total:1}
  while (allresults.length < result.total) {
    result = await npmsearch(`/query?q=${term}&from=${allresults.length}`)
    allresults = allresults.concat(result.results)
  }
  return allresults
}

const compact = downloads => {
  let months = {}
  downloads.forEach(day => {
    let m = day.date.slice(0, '2017-06'.length)
    if (!months[m]) months[m] = 0
    months[m] += day.value
  })
  return months
}

const getstats = name => {
  return new Promise((resolve, reject) => {
    registry.module(name).downloads((err, downloads) => {
      if (err) return reject(err)
      resolve(compact(downloads))
    })
  })
}

const run = async term => {
  const rows = []
  let months = new Set()
  let packages = await search(term)

  for (let pkg of packages) {
    let name = pkg.name[0]
    let downloads = await getstats(name)
    let row = {pkg: name}
    for (let [month, value] of Object.entries(downloads)) {
      let year = parseInt(month.slice(0, 4))
      if (year > 2015) {
        row[month] = value
        months.add(month)
      }
    }
    rows.push(row)
  }

  let headers = [
    {id: 'pkg', title: 'PKG'}
  ]
  headers = headers.concat(Array.from(months).sort().map(month => {
    return {id: month, title: month}
  }))

  const csvStringifier = createCsvStringifier({
    path: './test.csv',
    header: headers
  })
  console.log(csvStringifier.getHeaderString())
  console.log(csvStringifier.stringifyRecords(rows))
}
run('ipfs')
```

**Comment by pkafei** [comment]
This is good. 

I think we need to talk about which metrics we want to look at and why. For starters, I would like to focus on the growth from sites like Meetup, Telegram, and WeChat. I think you discussed this before, but I would like to have a community metric dashboard which shows:

a. Growth from month to month (for example there was 4% increase of participants who showed up at our North America IPFS meetups)

b. A screen that shows the latest comment from our Telegram or WeChat channel

c. Latest comments posted in our Reddit and Telegram from IPFS community members 

d. A call to action below the dashboard which encourages folks to (1. fix an issue in one of our repos, 2. Join in the Telegram conversation, 3. Create a meetup)

---

Would love to start writing preliminary code that grabs the amount of IPFS members and groups that reside on Meetup, Telegram, and WeChat

**Comment by terichadbourne** [comment]
I'd caution against any sort of "Create a Meetup" recommendation without a lot of context built in. Especially while our workshop content is still limited, I'd argue that we're much better off encouraging people to speak about IPFS in tangential Meetup groups (broader decentralized/P2P, Offline First, web dev, etc.) that have an existing audience, rather than suggesting that they create entire groups from scratch which will start with no audience and demand regular, ongoing content to meet the expectations members place on Meetup organizers. The number of people who know they're interested in IPFS (and would therefore join a new group) is a lot smaller than the number of folks who might discover they're interested if we meet them where they are in these related communities.

To this point, if there's a way to search individual meeting titles/descriptions rather than just group titles when gathering stats from Meetup, it would help to support the approach I'm proposing.

**Comment by pkafei** [comment]
I agree, I think for now we are better off encouraging people to speak about IPFS at their respective Meetup groups during the short-term. For the long term though, we would have a link that helps people get started in creating their own Meetup. For context, I'm thinking of something along the lines of [Node School ](https://nodeschool.io/) workshop section which helps Meetup organizers spawn a Meetup group from scratch.

**Comment by terichadbourne** [comment]
Our ProtoSchool site, which I'm working on, will have recommendations for hosting events, so that will be an appropriate place to link to from this dashboard, and we can decide what recommendations make sense there. For now, likely proposing one-off alternatives to building an entire Meetup group from scratch.
