### ISSUE TITLE
security and security audits

### ISSUE THREAD

**Issue by pgte** [ipfs/community#366]
Some people have been asking about security audits, so I think this may be important to communicate to the community.
They're asking specifically:

* Whether the crypto primitives that IPFS / libp2p uses (like the ones in libp2p-crypto) have been audited
* Whether specific protocols (like secio, Bitswap, pubs, etc.) have been audited
* Whether specific stacks (like peer-star and others) have been audited
* Whether specific apps (like peer-pad and others) have been audited
* If so, can we see the audit results
* Is there an IPFS Security Working Group?

**Comment by hsanjuan** [comment]
This question is a bit old but valid. I would like to direct people to ask in the right place and give the little info I have:

* Transports, crypto primitives, handshakes, dht etc falls to the libp2p project. The question is for a libp2p maintainer to answer and it's better asked at https://discuss.libp2p.io. I don't want to give any innacurate info on this regard.
* Peer-pad etc and other specific apps have probably not been audited (worth asking specifically to each app, since the security aspects of each are different).
* Bitswap, peer-star and other higher-level components have not been audited to my knowledge, worth asking directly in the respective repositories so that specific maintainers can respond.
* There is no IPFS Security WG right now, but security@ipfs.io can be used to communicate any issues.
