### ISSUE TITLE
Request for improvement suggestions for the 🙌🏽 IPFS Weekly Call 📞 

### ISSUE THREAD

**Issue by jennwrites** [ipfs/community#468]
## Question
We'd like to make sure IPFS Community calls and meetings are useful and efficient ways for the community to 1) learn about ecosystem projects being built with IPFS, 2) understand improvements to the core protocol landing in new releases, and 3) make cross-connections with likeminded projects and individuals to collaborate with. We'd like to revisit the structure and cadence of our [🙌🏽 IPFS Weekly Call 📞](https://github.com/ipfs/team-mgmt#-ipfs-weekly-call--formerly-known-as-ipfs-all-hands-call) to see whether it's still meeting those aims effectively - or if there are alternate ways to bring the community together on a regular cadence.

## Context
Over the past few months we've had a number of great presentations from teams like Fission, Berty, AnyType, EDGI, and others at the IPFS Weekly Call - however we've also noticed an increase in OpSec issues (notably 2 cases of [zoombombing](https://en.wikipedia.org/wiki/Zoombombing) on both the IPFS Office Hours and IPFS Weekly Call last week), scheduling issues, and technical difficulties with our recording/live streaming. 

Given that we are currently running _both_ Weekly Community Calls and Monthly IPFS Community Meetups, we're curious which community needs are best met by the Weekly Calls - and if there are ways to either change the call format, content, or schedule to better meet community needs.

## Proposal
Please help us evaluate community needs for regular gatherings by taking this very short survey: https://docs.google.com/forms/d/e/1FAIpQLSestacLPbEMvZp1KNtmSHC2Fk09sk1TQ2DUFzEIeE7-HK3QJA/viewform

**AND** please feel free to weigh in below with any suggestions for improving our regular community gatherings (format, technology, schedule, content, etc).

**Comment by autonome** [comment]
Thanks for starting the conversation here!

I'd like to separate a few things - addressing them independently might help get us to where we want to be:

* Goals: Why do we hold these? Worth asking, so that we all have a shared understanding of it - and will help align all the downtream questions

* Content: What the community want and need from these calls and meetups

* Frequency: Do we need both a monthly meetup *and* a weekly meeting

* Operations: How the current *weekly* meeting is run - the host system, the schedule, and all the various management/content/ops/quality/ownership challenges we've been having

The survey asks about all of these, so we'll get some more info once you send that out in the newsletter.

**Comment by jacobheun** [comment]
Can this be closed as we've transitioned to monthly, virtual meetups?

**Comment by autonome** [comment]
YES, fixed!
