### ISSUE TITLE
Hacking & Phishing  with ipfs.io 

### ISSUE THREAD

**Issue by 0xK3on** [ipfs/community#771]
I got an email with a link to your website which was clearly a phishing page.
You need to secure your website and clear your platform from abusive usage otherwise you will have a BIG trouble.
People are sending phishing emails linking to your website, example;

[https://fleek.ipfs.io/ipfs/Qme1nq51APWQMANeCrb5j9n4AxxW382e4ijeSkse8aEri1/excel%20link.html](https://fleek.ipfs.io/ipfs/Qme1nq51APWQMANeCrb5j9n4AxxW382e4ijeSkse8aEri1/excel%20link.html)

**Comment by domainfun** [comment]
Unfortunately, it appears that https://ipfs.io/ is unable to prevent spammers from misusing their system (just like Google Gmail and Microsoft Outlook.com allow any spammer to create a free account).  These big companies rely on the general public reporting any misuse, although I have no confidence that they actually remove misbehaving users in a timely manner (I speak from experience, when checking days after I reported phishing URLs to below email address in the past).

Perhaps on your incoming email service you can add a spam filter to block all emails containing `https://ipfs.io/ipfs/` or `https://fleek.ipfs.io/ipfs/` web addresses?

Anyway, rather than filing a ticket here on GitHub, please report these misuses to [abuse@ipfs.tech](mailto:abuse@ipfs.tech), see [https://ipfs.tech/help/](https://ipfs.tech/help/).

Here is another one from today (email address redacted for privacy):

`https://ipfs.io/ipfs/QmUKv5oL751qzcCSytJUGPf12k5hZkAspbVXSGevfvzM5y?filename=login.htm#...`

---- 

![20230720-2-phishing-email-with-link-to_https_ipfs io_ipfs_ login htm](https://github.com/ipfs/community/assets/46332757/a574ba28-32e5-4173-98c2-09d5f792b731)

![20230720-3-https_ipfs io_ipfs_ login htm](https://github.com/ipfs/community/assets/46332757/3375cf1b-7f25-4650-91ac-fd1a113b3e62)

**Comment by achingbrain** [comment]
Please see: https://github.com/ipfs/community/blob/master/SECURITY.md#reporting-abuse
